CREATE TABLE LOOK_BOOK (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR1 VARCHAR(255) NOT NULL,
    AUTHOR2 VARCHAR(255) NOT NULL,
    PHOTO_SHOOT_ID VARCHAR(255) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE PAYMENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PHOTO_SHOOT_ID VARCHAR(255) NOT NULL,
    AMOUNT DOUBLE NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SCHEDULE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PHOTO_SHOOT_ID VARCHAR(255) NOT NULL,
    START_DATE VARCHAR(50) NOT NULL,
    END_DATE VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE UPLOAD (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LOOK_BOOK_ID VARCHAR(255) NOT NULL,
    MIME_TYPE VARCHAR(255) NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    URL VARCHAR(255) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE PHOTO_SHOOT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);